### ISSUE TITLE
能问一下兄弟是怎么找到这个api的 要是我 我只能爬虫了

### ISSUE THREAD

**Issue by c834482351** [mokeeqian/wuhan-ncov#1]

**Comment by mokeeqian** [comment]
去丁香园，f12，network去分析一波就行啦

**Comment by mokeeqian** [comment]
爬虫我试过，懒得解析了，后来发现有轮子就不用重复造了

**Comment by c834482351** [comment]
> 去丁香园，f12，network去分析一波就行啦
关键是我咋没看出来那个是接口呢？

**Comment by c834482351** [comment]
找到api接口真的比用爬虫方便多了 大神能否详细说一下是怎么找到api的吗，便于我以后爬虫用，感激不尽！

**Comment by mokeeqian** [comment]
@c834482351 -  一般是通过f12，network选项卡跟踪XHR，来查看是否有数据请求。 
- flider抓包也可以 
- 之前一位老哥说过，移动端做抓包，爬虫要简单的很多

**Comment by c834482351** [comment]
> @c834482351 - 一般是通过f12，network选项卡跟踪XHR，来查看是否有数据请求。
> 
> * flider抓包也可以
> * 之前一位老哥说过，移动端做抓包，爬虫要简单的很多

好的谢谢老哥解答
